--
-- PostgreSQL database dump
--

\restrict 0RlU4Lp6cTyJzbmoQL6m1h91lx6hD6NqsMV8oZt29CWjCc09de9ikYgh7ha7oXO

-- Dumped from database version 14.19 (Debian 14.19-1.pgdg13+1)
-- Dumped by pg_dump version 17.6

-- Started on 2026-05-04 23:11:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3439 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 41011)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    balance numeric(14,2) NOT NULL,
    daily_balance numeric(9,2) NOT NULL,
    daily_balance_reset_date date NOT NULL,
    initial_balance numeric(14,2) NOT NULL,
    number character varying(6) NOT NULL,
    status boolean NOT NULL,
    type character varying(1) NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 41010)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 41016)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    password character varying(50) NOT NULL,
    status boolean NOT NULL,
    username character varying(25) NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 41022)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    age smallint NOT NULL,
    full_name character varying(100) NOT NULL,
    gender character varying(1) NOT NULL,
    id_number character varying(10) NOT NULL,
    phone character varying(10) NOT NULL
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 41021)
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 41028)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    id bigint NOT NULL,
    balance numeric(14,2) NOT NULL,
    date date NOT NULL,
    description character varying(50) NOT NULL,
    status boolean NOT NULL,
    type character varying(1) NOT NULL,
    value numeric(14,2) NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 41027)
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3428 (class 0 OID 41011)
-- Dependencies: 210
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account (id, balance, daily_balance, daily_balance_reset_date, initial_balance, number, status, type, customer_id) FROM stdin;
\.


--
-- TOC entry 3429 (class 0 OID 41016)
-- Dependencies: 211
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer (password, status, username, id) FROM stdin;
\.


--
-- TOC entry 3431 (class 0 OID 41022)
-- Dependencies: 213
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (id, address, age, full_name, gender, id_number, phone) FROM stdin;
\.


--
-- TOC entry 3433 (class 0 OID 41028)
-- Dependencies: 215
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction (id, balance, date, description, status, type, value, account_id) FROM stdin;
\.


--
-- TOC entry 3441 (class 0 OID 0)
-- Dependencies: 209
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 1, false);


--
-- TOC entry 3442 (class 0 OID 0)
-- Dependencies: 212
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 1, false);


--
-- TOC entry 3443 (class 0 OID 0)
-- Dependencies: 214
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_id_seq', 1, false);


--
-- TOC entry 3269 (class 2606 OID 41015)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 3274 (class 2606 OID 41020)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- TOC entry 3279 (class 2606 OID 41040)
-- Name: person id_number_index; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT id_number_index UNIQUE (id_number);


--
-- TOC entry 3272 (class 2606 OID 41035)
-- Name: account number_index; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT number_index UNIQUE (number);


--
-- TOC entry 3281 (class 2606 OID 41026)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 3284 (class 2606 OID 41032)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- TOC entry 3276 (class 2606 OID 41037)
-- Name: customer username_index; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT username_index UNIQUE (username);


--
-- TOC entry 3270 (class 1259 OID 41033)
-- Name: daily_balance_reset_date_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX daily_balance_reset_date_index ON public.account USING btree (daily_balance_reset_date);


--
-- TOC entry 3282 (class 1259 OID 41041)
-- Name: date_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX date_index ON public.transaction USING btree (date);


--
-- TOC entry 3277 (class 1259 OID 41038)
-- Name: full_name_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX full_name_index ON public.person USING btree (full_name);


--
-- TOC entry 3285 (class 2606 OID 41042)
-- Name: account fk_account_to_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_account_to_customer FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- TOC entry 3287 (class 2606 OID 41052)
-- Name: transaction fk_transaction_to_account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_transaction_to_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 3286 (class 2606 OID 41047)
-- Name: customer fk_user_to_person; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fk_user_to_person FOREIGN KEY (id) REFERENCES public.person(id);


--
-- TOC entry 3440 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2026-05-04 23:11:12

--
-- PostgreSQL database dump complete
--

\unrestrict 0RlU4Lp6cTyJzbmoQL6m1h91lx6hD6NqsMV8oZt29CWjCc09de9ikYgh7ha7oXO

